settings:
  title: 'LlamaNodes Monitoring'
  url: 'https://status.llamanodes.com/'
  logo: logo-192x192.png
  daysInHistogram: 90
  collectResponseTimes: true

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)'

monitors:
  - id: ETH
    name: Ethereum
    url: 'https://eth.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: POLYGON
    name: Polygon
    url: 'https://polygon.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: BNB
    name: BNB Chain
    url: 'https://binance.llamarpc.com/health'
    method: GET
    expectStatus: 200
