settings:
  title: 'LlamaNodes Monitoring'
  url: 'https://llamanodes.kindynos.mx/'
  logo: logo-192x192.png
  daysInHistogram: 90
  collectResponseTimes: true

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)'

monitors:
  - id: ETH
    name: Ethereum SKI
    url: 'https://eth-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: ARB
    name: Arbitrum SKI
    url: 'https://arbitrum-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: FTM
    name: Fantom SKI
    url: 'https://fantom-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: POLYGON
    name: Polygon SKI
    url: 'https://polygon-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: OPTIMISM
    name: Optimism SKI
    url: 'https://optimism-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: BSC
    name: BNB Chain SKI
    url: 'https://bsc-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: GNOSIS
    name: Gnosis Chain SKI
    url: 'https://gnosis-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: GOERLI
    name: Goerli SKI
    url: 'https://goerli-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
