settings:
  title: 'LlamaNodes Monitoring'
  url: 'https://llamanodes.kindynos.mx/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: ETH
    name: Ethereum RPC
    url: 'https://eth-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: ARB
    name: Arbitrum RPC
    url: 'https://arbitrum-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: FTM
    name: Fantom RPC
    url: 'https://ftm-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: POLYGON
    name: Polygon RPC
    url: 'https://polygon-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: OPTIMISM
    name: Optimism RPC
    url: 'https://optimism-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: BSC
    name: BNB Chain RPC
    url: 'https://bsc-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
  - id: GNOSIS
    name: Gnosis Chain RPC
    url: 'https://gnosis-ski.llamarpc.com/health'
    method: GET
    expectStatus: 200
